# Generated by Django 5.1.6 on 2025-03-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0002_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ru',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_site.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_site.course')),
            ],
        ),
    ]
