# Generated by Django 5.1.6 on 2025-03-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course_category', to='online_site.category'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='online_site.question'),
        ),
    ]
