# Generated by Django 5.1.6 on 2025-03-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0006_alter_course_category_alter_option_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='online_site.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='online_site.exam'),
        ),
    ]
